# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFHN3w-HULr2HkMojOZDuAY1eemfONcC
"""

import pandas as pd

df = pd.read_csv('/content/student_exam_performance_dataset (1).csv')

df.info()

df.isnull().sum()

"""### Creating a sample DataFrame with null values"""

import numpy as np

# Create a sample DataFrame with some null values
data = {
    'FeatureA': [1, 2, np.nan, 4, 5],
    'FeatureB': [6, np.nan, 8, 9, 10],
    'FeatureC': [11, 12, 13, np.nan, 15],
    'FeatureD': [16, 17, 18, 19, 20]
}
df_with_nulls = pd.DataFrame(data)

print("Sample DataFrame with null values:")
display(df_with_nulls)

print("\nInformation about the DataFrame:")
df_with_nulls.info()

print("\nNull values count:")
display(df_with_nulls.isnull().sum())

# Create a copy to avoid modifying the original DataFrame if it's used elsewhere
df_mean_imputed = df_with_nulls.copy()

# Get numerical columns
numerical_cols = df_mean_imputed.select_dtypes(include=np.number).columns

# Impute numerical columns with the mean
for col in numerical_cols:
    if df_mean_imputed[col].isnull().any(): # Check if the column has nulls
        mean_value = df_mean_imputed[col].mean()
        df_mean_imputed[col] = df_mean_imputed[col].fillna(mean_value)
        print(f"Filled nulls in column '{col}' with mean: {mean_value:.2f}")

print("\nDataFrame after mean imputation:")
display(df_mean_imputed)

print("\nNull values count after mean imputation:")
display(df_mean_imputed.isnull().sum())

"""### Applying Label Encoding to Categorical Columns"""

from sklearn.preprocessing import LabelEncoder

# Make a copy to avoid modifying the original DataFrame
df_encoded = df.copy()

# Identify categorical columns (object dtype)
categorical_cols = df_encoded.select_dtypes(include='object').columns

print("Categorical columns identified for encoding:", list(categorical_cols))

# Initialize LabelEncoder
le = LabelEncoder()

# Apply Label Encoding to each categorical column
for col in categorical_cols:
    # Display original value counts for one column before encoding
    if col == 'gender': # Choosing 'gender' as an example
        print(f"\nOriginal value counts for '{col}':")
        display(df_encoded[col].value_counts())

    df_encoded[col] = le.fit_transform(df_encoded[col])

    # Display encoded value counts for the same column after encoding
    if col == 'gender':
        print(f"\nEncoded value counts for '{col}':")
        display(df_encoded[col].value_counts())

print("\nDataFrame after Label Encoding:")
display(df_encoded.head())

print("\nInformation about the DataFrame after encoding:")
df_encoded.info()

"""### Separating Independent and Dependent Variables"""

# Define the dependent variable (target)
dependent_variable = 'final_exam_score'

# Create the independent variables (features) DataFrame (X)
X = df_encoded.drop(columns=[dependent_variable])

# Create the dependent variable (target) Series (y)
y = df_encoded[dependent_variable]

print(f"Shape of independent variables (X): {X.shape}")
print(f"Shape of dependent variable (y): {y.shape}")

print("\nFirst 5 rows of X:")
display(X.head())

print("\nFirst 5 rows of y:")
display(y.head())

"""### Splitting Data into Training and Testing Sets"""

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
# test_size=0.20 means 20% of the data will be used for testing, 80% for training
# random_state for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\nFirst 5 rows of X_train:")
display(X_train.head())

print("\nFirst 5 rows of y_train:")
display(y_train.head())

"""### Training and Evaluating Regression Models"""

from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Dictionary to store model performance metrics
model_performance = {}

def evaluate_model(model_name, y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    print(f"--- {model_name} ---")
    print(f"Mean Absolute Error (MAE): {mae:.2f}")
    print(f"R-squared (R2): {r2:.2f}")
    print("\n")
    model_performance[model_name] = {'MAE': mae, 'R2': r2}

"""#### 1. Linear Regression"""

# Initialize and train the model
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_lr = linear_reg_model.predict(X_test)

# Evaluate the model
evaluate_model("Linear Regression", y_test, y_pred_lr)

"""#### 2. Decision Tree Regressor"""

# Initialize and train the model
decision_tree_model = DecisionTreeRegressor(random_state=42)
decision_tree_model.fit(X_train, y_train)

# Make predictions
y_pred_dt = decision_tree_model.predict(X_test)

# Evaluate the model
evaluate_model("Decision Tree Regressor", y_test, y_pred_dt)

"""#### 3. Random Forest Regressor"""

# Initialize and train the model
random_forest_model = RandomForestRegressor(random_state=42)
random_forest_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = random_forest_model.predict(X_test)

# Evaluate the model
evaluate_model("Random Forest Regressor", y_test, y_pred_rf)

"""#### 4. Support Vector Machine (SVR)"""

# Scale the data for SVR
scaler_svr = StandardScaler()
X_train_scaled_svr = scaler_svr.fit_transform(X_train)
X_test_scaled_svr = scaler_svr.transform(X_test)

# Initialize and train the model
# Using a linear kernel for faster computation, consider rbf for potentially better but slower results
svr_model = SVR(kernel='linear')
svr_model.fit(X_train_scaled_svr, y_train)

# Make predictions
y_pred_svr = svr_model.predict(X_test_scaled_svr)

# Evaluate the model
evaluate_model("Support Vector Regressor (SVR)", y_test, y_pred_svr)

"""#### 5. K-Nearest Neighbors (KNN) Regressor"""

# Scale the data for KNN
scaler_knn = StandardScaler()
X_train_scaled_knn = scaler_knn.fit_transform(X_train)
X_test_scaled_knn = scaler_knn.transform(X_test)

# Initialize and train the model
knn_model = KNeighborsRegressor(n_neighbors=5) # n_neighbors can be tuned
knn_model.fit(X_train_scaled_knn, y_train)

# Make predictions
y_pred_knn = knn_model.predict(X_test_scaled_knn)

# Evaluate the model
evaluate_model("K-Nearest Neighbors Regressor (KNN)", y_test, y_pred_knn)

"""### Model Performance Visualization"""

import matplotlib.pyplot as plt
import seaborn as sns

# Convert the dictionary to a pandas DataFrame for easy plotting
performance_df = pd.DataFrame.from_dict(model_performance, orient='index')
performance_df = performance_df.reset_index().rename(columns={'index': 'Model'})

# Melt the DataFrame to plot MAE and R2 side-by-side
performance_melted = performance_df.melt(id_vars='Model', var_name='Metric', value_name='Score')

plt.figure(figsize=(14, 7))
sns.barplot(x='Model', y='Score', hue='Metric', data=performance_melted, palette='viridis')
plt.title('Comparison of Regression Model Performance (MAE and R2 Score)')
plt.ylabel('Score')
plt.xlabel('Model')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Metric')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Saving the Best Model"""

import pickle

# Assuming Linear Regression is chosen as the best model based on MAE and R2 scores
best_model = linear_reg_model

# Define the filename for the saved model
model_filename = 'linear_regression_model.pkl'

# Save the model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"Best model (Linear Regression) saved to {model_filename}")